version: "3.9"

services:
  nest-app:
    image: nest-sample-project:latest 
    container_name: nest-sample-project
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "2001:2001"   # Map container port 3000 → host port 3000
    networks:
      - "ci-network"
      
networks:
  ci-network:
    external: true
