version: "3.9"

services:
  nest-app:
    image: nest-sample-project:latest 
    container_name: nest-sample-project
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "20010:2001"   # Map container port 3000 → host port 3000
